### ISSUE TITLE
latest update broke it :(((

### ISSUE THREAD

**Issue by bootldrDNB** [flying-sausages/yapubfm#1]
after installing the latest version, the workflow has been moved from `services > general` to `services > pictures` and therefore no longer works as the script expects pictures.

:(

**Comment by flying-sausages** [comment]
derp should be fixed in 2c7a172, release pending @bootldrDNB

**Comment by bootldrDNB** [comment]
many thanks pal

**Comment by flying-sausages** [comment]
https://github.com/flying-sausages/yapubfm/releases/tag/0.2.2
